name: Build Limbo99 (push)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean Gradle caches (prevenção de bug Shadow)
        run: rm -rf ~/.gradle/caches

      - name: Build Limbo99 with ShadowJar
        run: ./gradlew clean shadowJar --no-daemon

      - name: Upload compiled plugin
        uses: actions/upload-artifact@v4
        with:
          name: Limbo99-build
          path: build/libs/*.jar
